### ISSUE TITLE
Create Rmd file tutorial for how to upload metadata for a new season

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#134]
This can go into the tutorials directory.

It should take three parameters:

1. url to google sheet template
2. url to shapefile
3. database connection (either dbcon object)

Outputs:

1. Insert metadata into database

**Comment by kimberlyh66** [comment]
First draft of tutorial [here](https://gist.github.com/kimberlyh66/c0b90ac4457e1a86f23608b403cbd423)

**Comment by kimberlyh66** [comment]
In the current draft of tutorial, I use a function to create a parameterized query for each row of a sheet (since provided inputs may vary from row to row).  

For example: `insert into experiments (name, start_date, end_date, user_id) values ($1, $2, $3, $4)` for one row  and `insert into experiments(name, start_date, end_date, description, user_id) values ($1, $2, $3, $4, $5)` for another. In this case, only one row can be inserted at once.

Do you think it would be better to create one version of a parameterized query for each table that can be used in all cases? If one version is used, then multiple rows can be inserted at once. However, I think something like `nullif` would have to be used on fields that are null by default and where the user does not provide a value.

For example: `insert into experiments (name, start_date, end_date, description, design, user_id) values ($1, nullif($2, NA)::date, nullif($3, NA)::date, $4, $5, $6)`.

**Comment by dlebauer** [comment]
@kimberlyh66 this is a nice start... could you please add this to the tutorials repository and create a pull request?

**Comment by kimberlyh66** [comment]
@dlebauer I have created pull request terraref/tutorials#135 - thanks for taking time to review

**Comment by kimberlyh66** [comment]
@dlebauer What should be next steps for this issue?

**Comment by dlebauer** [comment]
@kimberlyh66 next step is to update the code to use the R googlesheets package on published spreadsheets that don't require authentication.

**Comment by Chris-Schnaufer** [comment]
In Pull Request phase https://github.com/terraref/tutorials/pull/139
