### ISSUE TITLE
Create tutorial on how to run test database using docker

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#140]

**Comment by kimberlyh66** [comment]
See first draft of tutorial [here](https://gist.github.com/kimberlyh66/935106e35478829b9e844ba5b496784d).

@KristinaRiemer When you have time, can you see if you can get the test database running using this tutorial?

**Comment by KristinaRiemer** [comment]
This worked great! I was easily able to get it up and running. Thanks for including the steps for creating the override yml locally. 

A couple suggestions for content to add: 

1. Maybe add a "Purpose" section at the beginning of the tutorial describing why someone would want to do this. I'm assuming it's just for seeing if adding new data to the database works correctly? 

2. I would change line 19 to `git clone https://github.com/PecanProject/bety.git` so that the user doesn't have to worry about setting up ssh. 

3. In the "Step 1" section, I would include that PostgreSQL needs to be installed for this to work and include the link for downloading this (https://www.postgresql.org/download/). 

4. There's two places where it would be helpful to include what the user should expect to see if a step worked. I would include something like what I'm suggesting below in those places. 
- After line 51, it should display something like `bety_1      | I, [2019-04-19T19:50:36.948098 #8]  INFO -- : worker=0 ready` and then the cursor will be blinking on the next line. 
- After line 57, the following should be displayed, indicating the interactive console is ready for input: 
```
psql (11.2, server 9.5.16)
Type "help" for help.

bety=>```

Let me know if you have any questions about this or I'd be happy to implement some of these things.

**Comment by kimberlyh66** [comment]
@KristinaRiemer Thanks for the feedback! I will work on adding your suggestions.

**Comment by kimberlyh66** [comment]
Updated draft [here](https://gist.github.com/kimberlyh66/935106e35478829b9e844ba5b496784d)

**Comment by KristinaRiemer** [comment]
I think this looks great, and I don't have any more suggestions. Where is this going to be added?
