### ISSUE TITLE
Migrate TERRA REF documentation to Bookdown

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#155]

**Comment by kimberlyh66** [comment]
@dlebauer Can you provide more information on this issue? Should I be working in https://github.com/terraref/documentation repository?

**Comment by dlebauer** [comment]
yes, you can create a branch called 'bookdown' 

One step will be moving the organization in SUMMARY.md into _bookdown.yml. @ashiklom did this with the PEcAn documentation and may have some advice. We can also chat next week.

**Comment by ashiklom** [comment]
Happy to offer some thoughts, but I'm not totally sure what the goals are. Feel free to ping me here or on the PEcAn Slack if you have specific questions. In the meantime, here's the [source](https://github.com/PecanProject/pecan/tree/develop/book_source) of the PEcAn documentation.

Note that by default, all `.Rmd` files in the bookdown directory (and nested subdirectories, recursively) are rendered in alphabetical order. The alternative is to list files in the right order in the `_bookdown.yml` file. I personally recommend the former because (1) it guarantees you don't forget to render any `.Rmd` files, and (2) with well-defined rules, it makes it easier to navigate the documentation while editing (i.e. you don'y have to remember the order of chapters). The main disadvantage is that you often will have to rename multiple files if you want to insert any new chapters in the middle. This can be made substantially easier with a bit of bash wildcards and/or scripting.

**Comment by kimberlyh66** [comment]
@ashiklom Thanks for the advice. I'll let you know if I have any questions.

**Comment by kimberlyh66** [comment]
@dlebauer Would you rather have the `.Rmd` files listed in order in `_bookdown.yml` or have them rendered alphabetically? I would probably have to add `01-`, `02-`, etc. to the files / subdirectory names if they were to be rendered alphabetically.

**Comment by dlebauer** [comment]
Thanks @ashiklom for your advice - was there a step-by-step protocol or any existing tools to help with the migration that you used?

@kimberlyh66 I think for now we should not re-name the files there will be time to do that later. At the very least, it should be after I address the outstanding pull requests.

**Comment by ashiklom** [comment]
> was there a step-by-step protocol

No real protocol. There probably should have been one, we did it very informally.

> any existing tools

Not really. Mostly, just a Makefile and some ad-hoc shell scripts to make it easier to quickly rebuild the docs locally to see how it turned out. Knowing shell expansions is useful for quickly renumbering files.

**Comment by kimberlyh66** [comment]
See pull request terraref/documentation#198

**Comment by dlebauer** [comment]
Thank you Kimberly for exploring this option! After checking this out, along with new features on gitbook, I think we are going to stick with gitbook for the TERRA REF documentation.
