### ISSUE TITLE
Add tutorial for submitting jobs to processing pipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#159]
Create Jupyter Notebook example on how to submit a job w/ parameters to process drone images

**Comment by Chris-Schnaufer** [comment]
From Jeanette's feedback: 
- [ ] Remove empty code cell at the end of the file
- [ ] ... to include a link to a place where you can create/request a clowder account in the pre-reqs section

**Comment by KristinaRiemer** [comment]
This tutorial looks great! It was very easy to follow and the instructions are quite clear. The below list is just some suggestions, feel free to take or leave them as you see fit. 

1. **Audience** section should probably be more focused on the user's desired content instead of the required tools. I would have a couple sentences about the users wanting to use and process drone data, then maybe just a single sentence about them either having experience with Python and Jupyter NBs, or wanting to gain that experience. 
2. In **Prerequisites**, include a link to instructions for how to create a Clowder account, and maybe a link to an example of a loaded dataset? Also possibly a link to how to install `pipelineutils` if you think that's necessary. 
3. In **Step 1**, is there a Clowder URL that you can include as an example? Or just include a note pointing out the example dataset in **Prerequisites**. 
4. I might condense **Step 3** down to a list, something like the below. 

The additional required parameters are: 
* `username` and `password`: these are your Clowder login credentials
* `dataset`: the name of the loaded drone data to process
* `extractor`: shortened name of chosen extractor
* `space_name`: location where the resulting processed data will be organized

5. At first I didn't really like the redundancy between the text and the code comments, but I actually think that could be really useful to users. Some people might skim or not read the text and just go to the code, but then the instructions are right there. The only difficulty with the code comments is when they wrap to the next line, it looks a little confusing, but I'm not sure what to do about that because it depends on the size of the browser window? 
<img width="863" alt="Screen Shot 2019-06-13 at 10 29 01 AM" src="https://user-images.githubusercontent.com/6686508/59454354-b3bc1680-8dc6-11e9-8f6e-76d424384daf.png">

6. In **Step 4**, are the `config_file` and `odm_config` arguments the same thing? 
7. One of the things I've been thinking about a lot with all of these tutorials/vignettes is including showing the user that what they've done worked. In the case of this tutorial, how can they see/demonstrate that their call in **Step 5** worked? Can they check a Clowder URL or something? I might try to think about something along these lines to include in the tutorial.

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer Thanks for your feedback! As far as item 7 goes: the lack of feedback is a problem with the system overall that needs to be resolved. I wish there was something I could put here for verification that it worked, but there isn't anything

**Comment by Chris-Schnaufer** [comment]
Make pull request
